# Generated by Django 4.1 on 2022-08-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=240, verbose_name='FirstName')),
                ('m_name', models.CharField(max_length=240, verbose_name='MiddleName')),
                ('l_name', models.CharField(max_length=240, verbose_name='LastName')),
                ('email', models.EmailField(max_length=240, verbose_name='Email')),
                ('username', models.CharField(max_length=240, verbose_name='Username')),
                ('password', models.CharField(max_length=240, verbose_name='Password')),
                ('c_password', models.CharField(max_length=240, verbose_name='ConfirmPassword')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
    ]
